### ISSUE TITLE
translation files in multiple tarballs

### ISSUE THREAD

**Issue by sundeep-co-in** [transtats/transtats#187]
##### ISSUE TYPE

 - Bug Report

##### SUMMARY

There could be several `srpm` with translations `POs` bundled in multiple tarballs. This would be really challenging to attain uniformity as packaging style differs vastly.

One option could be to show statistics per tarball basis; but how to match them with a product release?

**Comment by sundeep-co-in** [comment]
linked with `downstreamsync` jobs!

**Comment by sundeep-co-in** [comment]
@smaitra-rh @juhp Please suggest.

**Comment by juhp** [comment]
I would suggest to combine the stats per package.
Isn't the concern more about how to process than how to show?

**Comment by sundeep-co-in** [comment]
> I would suggest to combine the stats per package.

this is what, we are doing now :)

> Isn't the concern more about how to process than how to show?

Actually, it's packaging style/requirements and there are various scenarios:
- one `srpm` may contain multiple projects hosted separately in Translation Platform.
- `srpm` may contain a separate `tar` only for translations.
- `srpm` may contain multiple set of translations in multiple tarballs. And doing some computation in `%prep` section of `spec` file.

there could be more examples.

**Comment by sundeep-anand** [comment]
with https://github.com/transtats/transtats/pull/235/commits/13c3c571630d255b16d7e986a6046bdb455fdc76 warning is shown when **filter** job_task finds translations in multiple dirs, and help user to select appropriate dir.

**Comment by sshedmake** [comment]
Following is a observation for the Red Hat Satellite 6.x package: ```rubygem-katello```

- One ```srpm``` contains two translation directories: 
```
   - data/engines/bastion/app/assets/javascripts/bastion/i18n/locale
   - data/locale
``` 
, targeting two projects: ```bastion_katello``` and  ```katello``` respectively, which are hosted separately over the Translation Platform.

- While launching: Job > Templates > Sync Package Build System, used following scenarios in Job Yaml filter, for the latest build of above package:

- **scenario_1**
```
  - filter:
    - name: files
    - domain: rubygem-katello
    - ext: PO
    - dir: 
```
- ```Calculated Stats``` table, showed stats for project ```bastion_katello``` or dir ```data/engines/bastion/app/assets/javascripts/bastion/i18n/locale``` only
- ```Calculated Stats``` table, did not show stats for project ```katello``` or dir ```data/locale```

- **scenario_2**
```
  - filter:
    - name: files
    - domain: katello
    - ext: PO
    - dir: data/locale
```
- ```Calculated Stats``` table, showed stats for project ```katello``` or dir ```data/locale``` only
- ```Calculated Stats``` table did not show stats for project ```bastion_katello``` or dir ```data/engines/bastion/app/assets/javascripts/bastion/i18n/locale```

- **scenario_3**
```
 - filter:
    - name: files
    - domain
         - rubygem-foreman
         - katello
    - ext: PO
    - dir
        - data/engines/bastion/app/assets/javascripts/bastion/i18n/locale
        - data/locale
```
- ```Calculated Stats``` table, showed stats for project ```bastion_katello``` or dir ```data/engines/bastion/app/assets/javascripts/bastion/i18n/locale``` only 
- ```Calculated Stats``` table did not show stats for project ```katello``` or dir ```data/locale```

<br>

- **Note_1**, in the Job Log (output): it correctly filters the PO files for the said ```dir``` value and calculate Translation Stats.

- Thereby, from above, suggesting to show ```Calculated Stats``` table, **per translation directory**.
